import "./global.css";
import { Provider } from "jotai";
// import { DevToolsProvider } from '@/providers/dev-tools';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import ReactQueryProvider from "../providers/tansk-query-provider";
import { NotificationProvider } from "@/components/custom/NotificationProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en">
        <body>
          <ReactQueryProvider>
            <NotificationProvider />
            {children}
          </ReactQueryProvider>
        </body>
      </html>
      {/* <DevToolsProvider /> */}
    </Provider>
  );
}
